name: buildx
on:
  pull_request:
    types: [closed]
    branches: master
  push:
    branches: master

jobs:
  build-client:
    runs-on: [windows-latest]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      - 
        name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
          architecture: x64
      - 
        name: Install Qt
        uses: jurplel/install-qt-action@v2.8.0
        with:
          install-deps: true
          modules: qtcharts qtwidgets qtgui qtcore
#      - name: Pip Installer
#        uses: BSFishy/pip-action@v1
#        with:
#          requirements: requirements.txt
      - name: PyInstaller Windows
        uses: JackMcKew/pyinstaller-action-windows@v0.1.2
        with:
          # Directory containing source code (optional requirements.txt).
          path: ./
          spec: docker/pyinstaller/client.spec
