name: Build Containers
on:
  pull_request:
    types: [closed]
    branches: master
  push:
    branches: master

jobs:
  build-client:
    runs-on: [ubuntu-latest]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2.3.4
      -
        name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v2
        with:
          images: |
            ghcr.io/hydrusnetwork/hydrus
          tags: |
            type=edge
            type=ref,event=pr
            type=semver,pattern={{raw}}
          labels: |
            org.opencontainers.image.title=Hydrus Network
            org.opencontainers.image.description=A personal booru-style media tagger that can import files and tags from your hard drive and popular websites.
            org.opencontainers.image.vendor=hydrusnetwork
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          buildkitd-flags: "--debug"
      -
        name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      #-
      #  name: Login to GHCR
      #  uses: docker/login-action@v1
      #  with:
      #    registry: ghcr.io
      #    username: ${{ secrets.GHCR_USERNAME }}
      #    password: ${{ secrets.GHCR_TOKEN }}
      -
        name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          file: ./static/build_files/docker/client/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/ppc64le,linux/386,linux/arm/v7
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
      -
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Move docker cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  build-server:
    runs-on: [ubuntu-latest]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2.3.4
      -
        name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v2
        with:
          images: |
            ghcr.io/hydrusnetwork/hydrus
          tags: |
            type=edge
            type=ref,event=pr
            type=semver,pattern={{raw}}
          flavor: |
            latest=false
            prefix=server-
          labels: |
            org.opencontainers.image.title=Hydrus Network Server
            org.opencontainers.image.description=A personal booru-style media tagger that can import files and tags from your hard drive and popular websites.
            org.opencontainers.image.vendor=hydrusnetwork
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          buildkitd-flags: "--debug"
      -
        name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      #-
      #  name: Login to GHCR
      #  uses: docker/login-action@v1
      #  with:
      #    registry: ghcr.io
      #    username: ${{ secrets.GHCR_USERNAME }}
      #    password: ${{ secrets.GHCR_TOKEN }}
      -
        name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          file: ./static/build_files/docker/server/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/ppc64le,linux/386,linux/arm/v7
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
      -
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Move docker cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache